insert into flight(id, duration) values (1, 100)
insert into flight(id, duration) values (2, 200)
insert into company(id, name) values (1, 'sicap')
insert into company(id, name) values (2, 'atos')
insert into company(id, name) values (3, 'orange')
