insert into flight(id, duration) values (1, 100)
insert into flight(id, duration) values (2, 200)
insert into company(id, name) values (1, 'sicap')
insert into company(id, name) values (2, 'atos')
insert into company(id, name) values (3, 'orange')
insert into drone(id, model, name, city) values (1, 'Alpha', 'ToTo', 'TOURNUS')
--insert into sensor( id, name, model) values (1, 'test', 'test')
--insert into drone(id, model, name, city) values (2, 'Bravo', 'Rajeux', 'MONTELIMAR')
--insert into drone(id, model, name, city) values (3, 'Charlie','Dodo', 'ROMANS')
--insert into drone(id, model, name, city) values (4, 'Delta', 'KasTo','VALENCE')